import './globals.css'
import './uno.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <footer>
        Made with 💞 by
        <span>
          <a href={'https://github.com/ffxixslh'} target="_blank">
            ffxixslh🤓
          </a>
        </span>
        &
        <span>
          <a href={'https://www.anthropic.com/product'} target="_blank">
            Claude🤖
          </a>
        </span>
      </footer>
    </html>
  )
}
